{extends layout.phtml}

{block #content}
<div id="submenu">
        <a href="{$baseUri}download/interlos2012.pdf" title="Interlos IV 2012">
                <img src="{$baseUri}download/interlos2012.jpg" alt="Interlos IV 2012" style="border: 1px solid #cecece; width:300px;"/>
        </a>
</div>
<div id="subcontent">
    <div class="flash info">
	<p><strong>Řešení</strong> najdete (včetně zdrojových kódů ukázkových implementací) na <a href="http://interlos.fi.muni.cz/download/years/2012/reseni/">http://interlos.fi.muni.cz/download/years/2012/reseni/</a>.</p>
	<p>
	<strong>Čtvrtý ročník interlosa</strong> je za námi a to i přes drobné karamboly doufáme, že jste si luštění, zuřivé programování a různě zapeklité úlohy užili a nezapomenete na nás v letech budoucích :D
		<br />
		Organizátoři INTERLOSA
	</p>
    </div>
<h2>Vítězové</h2>
<ul>
	<li>Vítězové celkově: <strong>Haluzná letargia</strong></li>
	<li>Vítězové v kategorii středoškoláci: <strong>Tábor LO</strong> (Luci, Maťa, Téra, Vašek, Zuzka)</li>
	<li>Vítězové v kategorii vysokoškoláci: <strong>Točená zmrzlina</strong> (Adam, Anna, Filip, Karel, Mirek)</li>
	<li>Vítězové v kategorii ostatní: <strong>Haluzná letargia</strong> (Danka, Janka, Mišof, Monika, YoYo)</li>
</ul>
<p><strong>Gratulujeme vítězům a těšíme se z účasti všech :-) Díky</strong>!</p>
<hr />
<ul>
        <li>Nejen informatická soutěž pořádaná <a href="http://fi.muni.cz" title="Fakulta informatiky MU Brno">Fakultou informatiky MU Brno</a></li>
        <li>Proběhla<strong style="font-size:2em"> v sobotu 1. 12. 2012, 15:00 - 20:00</strong></li>
        <li><strong>Registrace otevřena od 25. 10. 2012 do 30. 11. 2012!</strong></li>
        <li>
                Můžete se těšit na 27 rozmanitých, originálních úloh:
                <ul>
                        <li>Logické úlohy</li>
                        <li>Programátorské příklady</li>
                        <li>Šifry</li>
                        <li>Vyhledávání na internetu</li>
                </ul>
        </li>
        <li>Soutěžit budou 1-5 členné týmy ve třech kategoriích - středoškoláci, vysokoškoláci a ostatní.</li>
        <li>Účast je zcela zdarma</li>
        <li><strong>Hraje se o prestiž</strong></li>
</ul>
<p>
        Další informace najdete v <a href="{link :Frontend:Default:rules}">pravidlech</a>.
</p>


<p>
	Pokud máte jakýkoliv dotaz, připomínku, námět apod.,
	napište nám na naši adresu <a href="mailto:interlos@fi.muni.cz" style="font-size:1.5em">interlos@fi.muni.cz</a>
</p>

<div id="logos">
	<a href="http://muni.cz" title="Masarykova univerzita">
		<img src="http://ganymed.math.muni.cz/intersob/images/logo_mu.gif" alt="Masarykova univerzita"/>
	</a>
	<a href="http://fi.muni.cz" title="Fakulta informatiky MU">
		<img src="http://ganymed.math.muni.cz/intersob/images/logo_fi.gif" alt="Fakulta informatiky Masarykovy univerzity" />
	</a>
	<a href="http://ksi.fi.muni.cz" title="Korespondenční Seminář z Informatiky">
		<img src="{$baseUri}images/ksi-logo-final.png" alt="Korespondenční seminář z informatiky" style="display:inline" />
	</a>
</div>

<!--<h2>Korespondenční seminář z informatiky</h2>-->
<h2>Soutěž INTERLOS vám přináší</h2>
<p>Organizátoři <a href="http://ksi.fi.muni.cz" title="Korespondenční Seminář z Informatiky">Korespondenčního Semináře z Informatiky</a>, studenti a učitelé <a href="http://muni.cz" title="Masarykova univerzita">Masarykovy univerzity</a> a další:<br />
<em>Ondra Bouda, Honza Drábek, Tom Effenberger, Mirek Klimoš, Eva Krásenská, Heňo Lauko, Jiří Maara Marek, Peter Mroch Novák, Zuzka Petruchová, Béďa Said, Maja Svoreňová, Jana Tůmová, Martin Ukrop</em>
</p>

<!--<hr />

<h2>Gratulujeme vítězům ročníku 2010!</h2>
<ul>
        <li>
                <strong>Celkově</strong>
                <ol>
                        <li>voy-a-ger</li>
                        <li>Tykadla</li>
                        <li>Pomocná škola</li>
                </ol>
        </li><li>
                <strong>Středoškoláci</strong>
                <ol>
                        <li>Žufouni</li>
                        <li>Carpe Diem</li>
                        <li>Heuréka</li>
                </ol>
        </li><li>
                <strong>Vysokoškoláci</strong>
                <ol>
                        <li>voy-a-ger</li>
                        <li>Ešte se dohodneme</li>
                        <li>Pařížská modrá</li>
                </ol>
        </li><li>
                <strong>Ostatní</strong>
                <ol>
                        <li>Tykadla</li>
                        <li>Pomocná škola</li>
                        <li>Jeníčci</li>
                </ol>
        </li>
</ul>-->
</div>

<!--[if !IE]> -->
<object type="application/x-shockwave-flash" data="/images/banner_MQ2_960x100.swf" width="960" height="100">
<!-- <![endif]-->

<!--[if IE]>
<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="960" height="100">
  <param name="movie" value="/images/banner_MQ2_960x100.swf" />
  <!--><!--dgx-->
  <param name="loop" value="true" />
  <param name="menu" value="false" />
  <p>Nainstalujte prosím Flash plugin</p>
</object>
<!-- <![endif]-->

{/block}
