{extends layout.phtml}

{block #content}
     <div class="flash info">
             Nechcete pohořet a pořádně si Interlosa užít? Tak to hledáte na správném místě!
     </div>
     <h2>Šifry z předchozích ročníků</h2>
     <p>Naleznete na stránce <a href="{plink Default:lastYears}">minulé ročníky</a> spolu se vzorovými řešeními.</p>
{*     <h2>Příručka hráče</h2>
     <p>Dále jsme pro vás připravili herní <a href="http://interlos.fi.muni.cz/download/interlos-2011-prirucka-hrace.pdf">příručku</a>, ve které najdete spoustu užitečných tipů a rozehřívací příklady.</p>*}
{*     <h2>Jinde</h2>*}
{/block}
