{extends layout.phtml}

{block #subcontent}
<p>Zadání sad se v určený čas objeví na následujících adresách:</p>

<ul>
	<li>
		1. sada (od 15:00)
		<ul>
		    <li><a href="http://interlos.fi.muni.cz/download/years/2012/sada1/">http://interlos.fi.muni.cz/download/years/2012/sada1/</a></li>
		    <li>http://interlos.yavanna.cz/sada1/</li>
		    <li>http://www.fi.muni.cz/~xdrabek1/sada1/</li>
		</ul>
	</li>
	<li>
		2. sada (od 16:30)

		<ul>
			<li><a href="http://interlos.fi.muni.cz/download/years/2012/sada2/">http://interlos.fi.muni.cz/download/years/2012/sada2/</a></li>
			<li>http://interlos.yavanna.cz/sada2/</li>
			<li>http://www.fi.muni.cz/~xdrabek1/sada2/</li>
		</ul>
   </li>
	<li>
		3. sada (od 18:00)
		<ul>
			<li><a href="http://interlos.fi.muni.cz/download/years/2012/sada3/">http://interlos.fi.muni.cz/download/years/2012/sada3/</a></li>
			<li>http://interlos.yavanna.cz/sada3/</li>
			<li>http://www.fi.muni.cz/~xdrabek1/sada3/</li>

		</ul>
   </li>
</ul>
<p>
	Kdykoliv je v zadání uvedeno více alternativních webových adres, obsahují všechny adresy stejnou informaci a jsou uvedeny pouze pro zálohu (nikdy tedy není žádná úmyslně skrytá informace v rozdílech mezi verzemi).
</p>
<p>
	V případě výpadku serveru, na kterém běží systém hry nebo v případě opravy/upřesnění zadání obdržíte informace prostřednictvím stránky <a href="http://interlos.fi.muni.cz/download/years/2012/">interlos.fi.muni.cz/download/years/2012/</a> případně (v opravdu urgentních případech) e-mailem:
</p>

<p>
	A ještě několik rad:
</p>
<ul>
	<li>Pokud nemáte barevnou tiskárnu, mějte po ruce pastelky.</li>
	<li>Přečtěte si před hrou ještě jednou pravidla, ať máte jasno v bodování.</li>
	<li>Věnujte pozornost sekci "rady" v pravidlech.</li>
	<li>Zařazení příkladů v kategoriích (programátorské a počítačové, logické, šifry a nápadové) je pouze orientační. Klidně se může stát, že logickou úlohu vyřešíte počítačem a počítačovou úlohu tužkou.</li>
	<li>Připravte si dopředu dobrou svačinku a užijte si to.</li>
</ul>
{/block}
