<?xml version="1.0" encoding="utf-8" ?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs">
    <head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta http-equiv="content-language" content="cs" />
		<link rel="stylesheet" type="text/css" href="/css/main.css" />
		<link rel="stylesheet" type="text/css" href="/css/forms.css" />
		<link rel="stylesheet" type="text/css" href="/css/flashes.css" />
		<link href="/favicon.png" rel="icon" type="image/png" />
		<script type="text/javascript" src="/js/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="/js/jquery-ui-1.8.2.custom.min.js"></script>

		<title>
	    Interlos - Podrobné výsledky
		</title>

    </head>
    <body>
<div id="flashes">
</div><div id="score-stats-wrapper">
	<table id="score-stats" cellspacing="0">
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>1</td>
			<td class="team">Haluzná letargia</td>
			<td>
					28610
			</td>
			<td>
					4000
			</td>
			<td>
					80
			</td>
					<td class="done">998</td>
					<td class="done">1000</td>
					<td class="done">999</td>
					<td class="done">984</td>
					<td class="done">940</td>
					<td class="done">977</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="done">965</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="done">971</td>
					<td class="done">996</td>
					<td class="done">991</td>
					<td class="done">1000</td>
					<td class="done">991</td>
					<td class="done">995</td>
					<td class="done">998</td>
					<td class="done">998</td>
					<td class="done">994</td>
					<td class="done">992</td>
					<td class="done">979</td>
					<td class="done">1000</td>
					<td class="done">981</td>
					<td class="done">995</td>
					<td class="done">989</td>
		</tr>
			<tr class="line">
			<td>2</td>
			<td class="team">Pomocná škola</td>
			<td>
					24511
			</td>
			<td>
					3000
			</td>
			<td>
					110
			</td>
					<td class="done">999</td>
					<td class="done">996</td>
					<td class="done">978</td>
					<td class="done">974</td>
					<td class="done">918</td>
					<td class="done">987</td>
					<td class="done">978</td>
					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="done">1000</td>
					<td class="done">988</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">984</td>
					<td class="done">977</td>
					<td class="done">997</td>
					<td class="done">995</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="done">952</td>
					<td class="empty">X</td>
					<td class="done">1000</td>
					<td class="done">984</td>
		</tr>
			<tr class="line">
			<td>3</td>
			<td class="team">segmentation fault</td>
			<td>
					22984
			</td>
			<td>
					2500
			</td>
			<td>
					110
			</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="done">997</td>
					<td class="done">986</td>
					<td class="done">928</td>
					<td class="done">946</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="done">997</td>
					<td class="done">991</td>
					<td class="done">998</td>
					<td class="done">979</td>
					<td class="done">939</td>
					<td class="done">988</td>
					<td class="done">996</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="done">998</td>
					<td class="done">991</td>
					<td class="done">947</td>
					<td class="done">953</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">996</td>
		</tr>
			<tr class="line">
			<td>4</td>
			<td class="team">Točená zmrzlina</td>
			<td>
					22049
			</td>
			<td>
					2500
			</td>
			<td>
					90
			</td>
					<td class="done">994</td>
					<td class="done">999</td>
					<td class="done">995</td>
					<td class="done">994</td>
					<td class="done">974</td>
					<td class="empty">X</td>
					<td class="done">964</td>
					<td class="empty">X</td>
					<td class="done">958</td>
					<td class="done">993</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="done">994</td>
					<td class="done">1000</td>
					<td class="done">997</td>
					<td class="done">990</td>
					<td class="done">973</td>
					<td class="done">940</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">961</td>
		</tr>
			<tr class="line">
			<td>5</td>
			<td class="team">Tykadla</td>
			<td>
					21231
			</td>
			<td>
					2500
			</td>
			<td>
					20
			</td>
					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="done">1000</td>
					<td class="done">1000</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="done">977</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="done">965</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">1000</td>
					<td class="done">954</td>
					<td class="done">955</td>
					<td class="done">1000</td>
					<td class="done">998</td>
					<td class="done">967</td>
		</tr>
			<tr class="line">
			<td>6</td>
			<td class="team">Haluzná megakombinácia</td>
			<td>
					20096
			</td>
			<td>
					2500
			</td>
			<td>
					140
			</td>
					<td class="done">993</td>
					<td class="done">991</td>
					<td class="done">993</td>
					<td class="done">978</td>
					<td class="done">949</td>
					<td class="done">989</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="done">995</td>
					<td class="done">990</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="done">981</td>
					<td class="done">974</td>
					<td class="done">997</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="done">1000</td>
		</tr>
			<tr class="line">
			<td>7</td>
			<td class="team">Přizdisráči</td>
			<td>
					20079
			</td>
			<td>
					2500
			</td>
			<td>
					160
			</td>
					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="done">968</td>
					<td class="done">982</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">983</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">944</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="done">987</td>
					<td class="done">998</td>
					<td class="done">997</td>
					<td class="done">998</td>
		</tr>
			<tr class="line">
			<td>8</td>
			<td class="team">nechci-uvést</td>
			<td>
					19593
			</td>
			<td>
					2000
			</td>
			<td>
					40
			</td>
					<td class="empty">X</td>
					<td class="done">957</td>
					<td class="done">981</td>
					<td class="done">990</td>
					<td class="done">975</td>
					<td class="done">972</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="done">1000</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">975</td>
					<td class="done">928</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="done">985</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="done">939</td>
		</tr>
			<tr class="line">
			<td>9</td>
			<td class="team">2B|~2B</td>
			<td>
					18473
			</td>
			<td>
					2000
			</td>
			<td>
					180
			</td>
					<td class="done">1000</td>
					<td class="done">953</td>
					<td class="done">989</td>
					<td class="done">980</td>
					<td class="done">933</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">965</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
					<td class="done">946</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">931</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="done">999</td>
		</tr>
			<tr class="line">
			<td>10</td>
			<td class="team">Finální myšmaš</td>
			<td>
					18453
			</td>
			<td>
					2000
			</td>
			<td>
					90
			</td>
					<td class="done">996</td>
					<td class="done">941</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="done">936</td>
					<td class="done">951</td>
					<td class="done">988</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="done">974</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="done">982</td>
					<td class="done">996</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="done">949</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">928</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>11</td>
			<td class="team">Mme Petak&#039;s Lonely Hearts Club Band</td>
			<td>
					18446
			</td>
			<td>
					2000
			</td>
			<td>
					250
			</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="done">981</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="done">961</td>
					<td class="empty">X</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
					<td class="done">962</td>
					<td class="done">978</td>
					<td class="done">994</td>
					<td class="done">988</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="done">988</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="done">950</td>
		</tr>
			<tr class="line">
			<td>12</td>
			<td class="team">voy-a-ger</td>
			<td>
					18168
			</td>
			<td>
					2500
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="done">967</td>
					<td class="empty">X</td>
					<td class="done">974</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="done">983</td>
					<td class="done">992</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">967</td>
					<td class="done">980</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="done">982</td>
		</tr>
			<tr class="line">
			<td>13</td>
			<td class="team">Jahodaaa</td>
			<td>
					17631
			</td>
			<td>
					2000
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="done">990</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="done">973</td>
					<td class="done">972</td>
					<td class="done">973</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="done">962</td>
		</tr>
			<tr class="line">
			<td>14</td>
			<td class="team">žufouni</td>
			<td>
					17022
			</td>
			<td>
					1500
			</td>
			<td>
					130
			</td>
					<td class="empty">X</td>
					<td class="done">948</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">938</td>
					<td class="done">971</td>
					<td class="done">981</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">975</td>
					<td class="done">997</td>
					<td class="done">990</td>
					<td class="done">966</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="done">971</td>
					<td class="done">966</td>
					<td class="done">996</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="done">968</td>
		</tr>
			<tr class="line">
			<td>15</td>
			<td class="team">Rohozky</td>
			<td>
					16589
			</td>
			<td>
					2000
			</td>
			<td>
					80
			</td>
					<td class="done">995</td>
					<td class="done">968</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">973</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">956</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="done">937</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">968</td>
					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="done">971</td>
					<td class="done">998</td>
					<td class="done">990</td>
					<td class="empty">X</td>
					<td class="done">964</td>
		</tr>
			<tr class="line">
			<td>16</td>
			<td class="team">Sráči</td>
			<td>
					15120
			</td>
			<td>
					1500
			</td>
			<td>
					40
			</td>
					<td class="empty">X</td>
					<td class="done">954</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="done">971</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="done">971</td>
					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="done">969</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="done">982</td>
					<td class="done">933</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">980</td>
		</tr>
			<tr class="line">
			<td>17</td>
			<td class="team">Bazinga</td>
			<td>
					15090
			</td>
			<td>
					1500
			</td>
			<td>
					80
			</td>
					<td class="empty">X</td>
					<td class="done">943</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="done">925</td>
					<td class="empty">X</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="done">975</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="done">977</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">979</td>
		</tr>
			<tr class="line">
			<td>18</td>
			<td class="team">Nejnekvazidiagonalizovávatelnější</td>
			<td>
					14936
			</td>
			<td>
					1500
			</td>
			<td>
					80
			</td>
					<td class="done">997</td>
					<td class="done">935</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">923</td>
					<td class="empty">X</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="done">980</td>
					<td class="done">981</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">925</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">951</td>
					<td class="done">925</td>
					<td class="done">993</td>
					<td class="done">996</td>
					<td class="done">953</td>
		</tr>
			<tr class="line">
			<td>19</td>
			<td class="team">kancl</td>
			<td>
					14606
			</td>
			<td>
					2000
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="done">996</td>
					<td class="done">975</td>
					<td class="done">945</td>
					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="done">998</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="done">956</td>
					<td class="done">912</td>
					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="done">958</td>
		</tr>
			<tr class="line">
			<td>20</td>
			<td class="team">Jeníčci</td>
			<td>
					14580
			</td>
			<td>
					2000
			</td>
			<td>
					110
			</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="done">922</td>
					<td class="empty">X</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">950</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="done">957</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">948</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>21</td>
			<td class="team">KVÍK!</td>
			<td>
					14161
			</td>
			<td>
					1500
			</td>
			<td>
					50
			</td>
					<td class="empty">X</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="done">976</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
					<td class="done">967</td>
					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">929</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="done">951</td>
		</tr>
			<tr class="line">
			<td>22</td>
			<td class="team">Lososi na sněhu</td>
			<td>
					14045
			</td>
			<td>
					1500
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>
					<td class="done">963</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="done">964</td>
					<td class="done">957</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="done">978</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="done">953</td>
					<td class="done">929</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">992</td>
		</tr>
			<tr class="line">
			<td>23</td>
			<td class="team">ROFLCOPTER!</td>
			<td>
					14012
			</td>
			<td>
					500
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>
					<td class="done">967</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">955</td>
					<td class="done">980</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="done">962</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">965</td>
					<td class="done">916</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="done">992</td>
					<td class="done">958</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="done">972</td>
		</tr>
			<tr class="line">
			<td>24</td>
			<td class="team">zúfalci</td>
			<td>
					13983
			</td>
			<td>
					1500
			</td>
			<td>
					40
			</td>
					<td class="empty">X</td>
					<td class="done">930</td>
					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="done">963</td>
					<td class="done">954</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">950</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="done">988</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="done">952</td>
					<td class="done">934</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="done">956</td>
		</tr>
			<tr class="line">
			<td>25</td>
			<td class="team">Kapela pamětníků</td>
			<td>
					13972
			</td>
			<td>
					1500
			</td>
			<td>
					120
			</td>
					<td class="done">992</td>
					<td class="done">974</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">954</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">957</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">961</td>
					<td class="done">951</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="done">964</td>
					<td class="done">942</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">933</td>
		</tr>
			<tr class="line">
			<td>26</td>
			<td class="team">Harmonický bagr</td>
			<td>
					13597
			</td>
			<td>
					1000
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">953</td>
					<td class="done">966</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">969</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">973</td>
					<td class="done">963</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="done">991</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">935</td>
		</tr>
			<tr class="line">
			<td>27</td>
			<td class="team">Error 37</td>
			<td>
					13577
			</td>
			<td>
					1000
			</td>
			<td>
					80
			</td>
					<td class="empty">X</td>
					<td class="done">936</td>
					<td class="done">994</td>
					<td class="done">985</td>
					<td class="done">950</td>
					<td class="empty">X</td>
					<td class="done">961</td>
					<td class="empty">X</td>
					<td class="done">968</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="done">1000</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="done">961</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">943</td>
		</tr>
			<tr class="line">
			<td>28</td>
			<td class="team">Carpe Diem</td>
			<td>
					13566
			</td>
			<td>
					1000
			</td>
			<td>
					140
			</td>
					<td class="empty">X</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="done">985</td>
					<td class="done">965</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="done">935</td>
					<td class="empty">X</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="done">923</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">986</td>
		</tr>
			<tr class="line">
			<td>29</td>
			<td class="team">Lišky ve vaně</td>
			<td>
					13480
			</td>
			<td>
					1000
			</td>
			<td>
					50
			</td>
					<td class="empty">X</td>
					<td class="done">947</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">920</td>
					<td class="empty">X</td>
					<td class="done">963</td>
					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="done">954</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">932</td>
					<td class="done">990</td>
					<td class="done">993</td>
					<td class="done">989</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">968</td>
					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">932</td>
		</tr>
			<tr class="line">
			<td>30</td>
			<td class="team">Spící Volové</td>
			<td>
					13203
			</td>
			<td>
					1500
			</td>
			<td>
					20
			</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="done">998</td>
					<td class="done">980</td>
					<td class="done">988</td>
					<td class="done">968</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="done">958</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">965</td>
					<td class="done">968</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">963</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>31</td>
			<td class="team">Dršťkový Havran Masového Kašpárka</td>
			<td>
					12605
			</td>
			<td>
					1000
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="done">926</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">946</td>
					<td class="done">962</td>
					<td class="done">973</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="done">962</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">980</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">1000</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">975</td>
		</tr>
			<tr class="line">
			<td>32</td>
			<td class="team">divize nulou</td>
			<td>
					12514
			</td>
			<td>
					1000
			</td>
			<td>
					50
			</td>
					<td class="empty">X</td>
					<td class="done">944</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="done">990</td>
					<td class="done">979</td>
					<td class="done">962</td>
					<td class="empty">X</td>
					<td class="done">947</td>
					<td class="done">952</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">991</td>
					<td class="done">936</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">938</td>
		</tr>
			<tr class="line">
			<td>33</td>
			<td class="team">Night Wolves</td>
			<td>
					12168
			</td>
			<td>
					1500
			</td>
			<td>
					80
			</td>
					<td class="empty">X</td>
					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="done">937</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">983</td>
					<td class="done">967</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">950</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">990</td>
		</tr>
			<tr class="line">
			<td>34</td>
			<td class="team">Ovce</td>
			<td>
					12137
			</td>
			<td>
					500
			</td>
			<td>
					40
			</td>
					<td class="empty">X</td>
					<td class="done">927</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="done">973</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="done">957</td>
					<td class="done">964</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="done">952</td>
		</tr>
			<tr class="line">
			<td>35</td>
			<td class="team">Ešte sa dohodneme</td>
			<td>
					12111
			</td>
			<td>
					1500
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="done">985</td>
					<td class="done">983</td>
					<td class="done">961</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">998</td>
					<td class="done">956</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="done">913</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">957</td>
		</tr>
			<tr class="line">
			<td>36</td>
			<td class="team">dušou blondínky</td>
			<td>
					12050
			</td>
			<td>
					500
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="done">950</td>
					<td class="done">966</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">952</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="done">980</td>
					<td class="done">926</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="done">983</td>
		</tr>
			<tr class="line">
			<td>37</td>
			<td class="team">Supermuf</td>
			<td>
					12039
			</td>
			<td>
					1500
			</td>
			<td>
					80
			</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="done">950</td>
					<td class="done">964</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">915</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">959</td>
					<td class="done">962</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">985</td>
		</tr>
			<tr class="line">
			<td>38</td>
			<td class="team">Šestý nesmysl</td>
			<td>
					11667
			</td>
			<td>
					1000
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="done">957</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="done">976</td>
					<td class="done">956</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">954</td>
		</tr>
			<tr class="line">
			<td>39</td>
			<td class="team">Tábor LO</td>
			<td>
					11641
			</td>
			<td>
					1000
			</td>
			<td>
					30
			</td>
					<td class="empty">X</td>
					<td class="done">973</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">947</td>
					<td class="done">947</td>
					<td class="done">967</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="done">983</td>
					<td class="done">967</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">949</td>
		</tr>
			<tr class="line">
			<td>40</td>
			<td class="team">VYPLS</td>
			<td>
					11616
			</td>
			<td>
					1000
			</td>
			<td>
					60
			</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="done">949</td>
					<td class="done">968</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="done">940</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">969</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="done">946</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>41</td>
			<td class="team">Tweety neni kura!</td>
			<td>
					11563
			</td>
			<td>
					1000
			</td>
			<td>
					110
			</td>
					<td class="empty">X</td>
					<td class="done">961</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">983</td>
					<td class="done">955</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">951</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">974</td>
					<td class="done">958</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="done">985</td>
					<td class="done">947</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>42</td>
			<td class="team">H</td>
			<td>
					11062
			</td>
			<td>
					500
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="empty">X</td>
					<td class="done">946</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="done">918</td>
					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="done">974</td>
					<td class="done">978</td>
					<td class="empty">X</td>
					<td class="done">970</td>
		</tr>
			<tr class="line">
			<td>43</td>
			<td class="team">Jak se nám líbí!</td>
			<td>
					10654
			</td>
			<td>
					1000
			</td>
			<td>
					50
			</td>
					<td class="empty">X</td>
					<td class="done">940</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">948</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="done">935</td>
					<td class="done">988</td>
					<td class="empty">X</td>
					<td class="done">955</td>
		</tr>
			<tr class="line">
			<td>44</td>
			<td class="team">Diamhra</td>
			<td>
					10643
			</td>
			<td>
					1000
			</td>
			<td>
					10
			</td>
					<td class="empty">X</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">958</td>
					<td class="done">973</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="done">963</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">964</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">948</td>
					<td class="done">978</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="done">934</td>
		</tr>
			<tr class="line">
			<td>45</td>
			<td class="team">PPP</td>
			<td>
					10641
			</td>
			<td>
					1000
			</td>
			<td>
					110
			</td>
					<td class="empty">X</td>
					<td class="done">951</td>
					<td class="done">988</td>
					<td class="empty">X</td>
					<td class="done">991</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="done">988</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">920</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">998</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">947</td>
		</tr>
			<tr class="line">
			<td>46</td>
			<td class="team">Vepřová kachna</td>
			<td>
					10626
			</td>
			<td>
					1000
			</td>
			<td>
					60
			</td>
					<td class="empty">X</td>
					<td class="done">937</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">965</td>
					<td class="done">956</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">949</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">964</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">987</td>
		</tr>
			<tr class="line">
			<td>47</td>
			<td class="team">10100111001</td>
			<td>
					10611
			</td>
			<td>
					1000
			</td>
			<td>
					150
			</td>
					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">943</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="done">967</td>
					<td class="done">990</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">975</td>
					<td class="done">954</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>48</td>
			<td class="team">Brutální Drtiči</td>
			<td>
					10581
			</td>
			<td>
					1000
			</td>
			<td>
					130
			</td>
					<td class="empty">X</td>
					<td class="done">956</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">934</td>
					<td class="done">960</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">948</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="done">982</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>49</td>
			<td class="team">Geek Squad</td>
			<td>
					10576
			</td>
			<td>
					1000
			</td>
			<td>
					140
			</td>
					<td class="empty">X</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">932</td>
					<td class="done">967</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="done">968</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">973</td>
		</tr>
			<tr class="line">
			<td>50</td>
			<td class="team">Embargo na IQtIQ</td>
			<td>
					10540
			</td>
			<td>
					1000
			</td>
			<td>
					170
			</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">955</td>
					<td class="done">955</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="done">978</td>
					<td class="empty">X</td>
					<td class="done">974</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="done">990</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">936</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>51</td>
			<td class="team">para-N-methylaminoazobenzen</td>
			<td>
					10138
			</td>
			<td>
					500
			</td>
			<td>
					60
			</td>
					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="done">982</td>
					<td class="done">974</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">963</td>
					<td class="done">991</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="empty">X</td>
					<td class="done">922</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">930</td>
		</tr>
			<tr class="line">
			<td>52</td>
			<td class="team">Sloniky</td>
			<td>
					10047
			</td>
			<td>
					500
			</td>
			<td>
					130
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">956</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="done">964</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="done">924</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">963</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">942</td>
		</tr>
			<tr class="line">
			<td>53</td>
			<td class="team">Maséři jako hovado</td>
			<td>
					9978
			</td>
			<td>
					500
			</td>
			<td>
					120
			</td>
					<td class="empty">X</td>
					<td class="done">962</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">929</td>
					<td class="done">990</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="done">963</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">921</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">958</td>
					<td class="done">939</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">960</td>
		</tr>
			<tr class="line">
			<td>54</td>
			<td class="team">Myšlenka Ryby</td>
			<td>
					9703
			</td>
			<td>
					1000
			</td>
			<td>
					90
			</td>
					<td class="empty">X</td>
					<td class="done">934</td>
					<td class="done">977</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">965</td>
		</tr>
			<tr class="line">
			<td>55</td>
			<td class="team">6c1533306803e108</td>
			<td>
					9667
			</td>
			<td>
					1000
			</td>
			<td>
					30
			</td>
					<td class="empty">X</td>
					<td class="done">955</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="done">919</td>
					<td class="done">963</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="done">974</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">945</td>
		</tr>
			<tr class="line">
			<td>56</td>
			<td class="team">Stěrači</td>
			<td>
					9629
			</td>
			<td>
					0
			</td>
			<td>
					220
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="done">970</td>
					<td class="done">998</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">994</td>
		</tr>
			<tr class="line">
			<td>57</td>
			<td class="team">Dostál</td>
			<td>
					9574
			</td>
			<td>
					1000
			</td>
			<td>
					110
			</td>
					<td class="empty">X</td>
					<td class="done">922</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="done">939</td>
					<td class="empty">X</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">961</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">981</td>
		</tr>
			<tr class="line">
			<td>58</td>
			<td class="team">BSOD</td>
			<td>
					9523
			</td>
			<td>
					1000
			</td>
			<td>
					180
			</td>
					<td class="empty">X</td>
					<td class="done">933</td>
					<td class="empty">X</td>
					<td class="done">991</td>
					<td class="done">962</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">954</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">998</td>
					<td class="done">926</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>59</td>
			<td class="team">Ideální make-up</td>
			<td>
					9440
			</td>
			<td>
					1000
			</td>
			<td>
					190
			</td>
					<td class="empty">X</td>
					<td class="done">949</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">917</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">951</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">945</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">983</td>
					<td class="done">918</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="done">979</td>
		</tr>
			<tr class="line">
			<td>60</td>
			<td class="team">Dríím Tíím</td>
			<td>
					9157
			</td>
			<td>
					500
			</td>
			<td>
					50
			</td>
					<td class="empty">X</td>
					<td class="done">931</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">973</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">1000</td>
					<td class="done">962</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">969</td>
					<td class="done">969</td>
					<td class="done">951</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">974</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>61</td>
			<td class="team">Zebra řez</td>
			<td>
					8743
			</td>
			<td>
					1000
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="done">990</td>
					<td class="done">989</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">952</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">966</td>
		</tr>
			<tr class="line">
			<td>62</td>
			<td class="team">Laserová Prasátka</td>
			<td>
					8676
			</td>
			<td>
					0
			</td>
			<td>
					40
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">906</td>
					<td class="done">949</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="done">974</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">950</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">995</td>
		</tr>
			<tr class="line">
			<td>63</td>
			<td class="team">Vopice</td>
			<td>
					8224
			</td>
			<td>
					500
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="done">946</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">949</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>64</td>
			<td class="team">Soubor kreténů</td>
			<td>
					8063
			</td>
			<td>
					500
			</td>
			<td>
					30
			</td>
					<td class="empty">X</td>
					<td class="done">928</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">924</td>
					<td class="empty">X</td>
					<td class="done">965</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="done">942</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">917</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">969</td>
		</tr>
			<tr class="line">
			<td>65</td>
			<td class="team">A - Team OKAPP</td>
			<td>
					8008
			</td>
			<td>
					500
			</td>
			<td>
					200
			</td>
					<td class="empty">X</td>
					<td class="done">923</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="done">978</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">953</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">927</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">962</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">991</td>
		</tr>
			<tr class="line">
			<td>66</td>
			<td class="team">V.I.Peace</td>
			<td>
					7853
			</td>
			<td>
					500
			</td>
			<td>
					210
			</td>
					<td class="empty">X</td>
					<td class="done">924</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">915</td>
					<td class="done">952</td>
					<td class="done">958</td>
					<td class="empty">X</td>
					<td class="done">953</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">967</td>
					<td class="done">957</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">937</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>67</td>
			<td class="team">Škrkny</td>
			<td>
					7685
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="done">969</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">941</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="done">944</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">931</td>
		</tr>
			<tr class="line">
			<td>68</td>
			<td class="team">Dáme harásek</td>
			<td>
					7672
			</td>
			<td>
					0
			</td>
			<td>
					110
			</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">942</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="done">922</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>69</td>
			<td class="team">Tykve</td>
			<td>
					7193
			</td>
			<td>
					500
			</td>
			<td>
					60
			</td>
					<td class="empty">X</td>
					<td class="done">965</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">916</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">977</td>
		</tr>
			<tr class="line">
			<td>70</td>
			<td class="team">Hlavy otevřené</td>
			<td>
					7072
			</td>
			<td>
					500
			</td>
			<td>
					170
			</td>
					<td class="empty">X</td>
					<td class="done">929</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">921</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="done">943</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">988</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>71</td>
			<td class="team">PLKH</td>
			<td>
					6954
			</td>
			<td>
					500
			</td>
			<td>
					120
			</td>
					<td class="empty">X</td>
					<td class="done">932</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">909</td>
					<td class="done">957</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">968</td>
					<td class="done">919</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">930</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">959</td>
		</tr>
			<tr class="line">
			<td>72</td>
			<td class="team">Chróúst?!</td>
			<td>
					6755
			</td>
			<td>
					0
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">961</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">965</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="done">997</td>
		</tr>
			<tr class="line">
			<td>73</td>
			<td class="team">Alea</td>
			<td>
					6537
			</td>
			<td>
					0
			</td>
			<td>
					240
			</td>
					<td class="empty">X</td>
					<td class="done">938</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="done">948</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">957</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="done">948</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>74</td>
			<td class="team">Stoosum</td>
			<td>
					6199
			</td>
			<td>
					500
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>
					<td class="done">945</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">917</td>
					<td class="done">981</td>
					<td class="empty">X</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>75</td>
			<td class="team">Svědkové Baronovi</td>
			<td>
					6157
			</td>
			<td>
					500
			</td>
			<td>
					80
			</td>
					<td class="empty">X</td>
					<td class="done">952</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">902</td>
					<td class="done">975</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">941</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>76</td>
			<td class="team">a spol.</td>
			<td>
					6105
			</td>
			<td>
					500
			</td>
			<td>
					50
			</td>
					<td class="empty">X</td>
					<td class="done">925</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">914</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">923</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">955</td>
					<td class="done">946</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>77</td>
			<td class="team">Sobí bratři</td>
			<td>
					6016
			</td>
			<td>
					500
			</td>
			<td>
					240
			</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">951</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">938</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">927</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">977</td>
		</tr>
			<tr class="line">
			<td>78</td>
			<td class="team">ὅπερ ἔδει δεῖξαι</td>
			<td>
					5796
			</td>
			<td>
					0
			</td>
			<td>
					20
			</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="done">930</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">933</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>79</td>
			<td class="team">Žabaryba</td>
			<td>
					5743
			</td>
			<td>
					0
			</td>
			<td>
					30
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="done">914</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">980</td>
					<td class="done">993</td>
					<td class="done">915</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>80</td>
			<td class="team">Kajakteam</td>
			<td>
					5638
			</td>
			<td>
					0
			</td>
			<td>
					80
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">973</td>
					<td class="done">935</td>
					<td class="done">958</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="done">947</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">928</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>81</td>
			<td class="team">No Chance</td>
			<td>
					5556
			</td>
			<td>
					500
			</td>
			<td>
					590
			</td>
					<td class="empty">X</td>
					<td class="done">939</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">931</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="done">934</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">932</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">940</td>
		</tr>
			<tr class="line">
			<td>82</td>
			<td class="team">Bedrunky</td>
			<td>
					5198
			</td>
			<td>
					500
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">914</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">929</td>
		</tr>
			<tr class="line">
			<td>83</td>
			<td class="team">Zrychlený TEP</td>
			<td>
					5109
			</td>
			<td>
					500
			</td>
			<td>
					110
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">910</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">963</td>
					<td class="done">936</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">944</td>
		</tr>
			<tr class="line">
			<td>84</td>
			<td class="team">FTA</td>
			<td>
					5086
			</td>
			<td>
					500
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="done">942</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">913</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">943</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">921</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">937</td>
		</tr>
			<tr class="line">
			<td>85</td>
			<td class="team">:(){ :|:&amp; };:</td>
			<td>
					4755
			</td>
			<td>
					0
			</td>
			<td>
					80
			</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="done">944</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">961</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">967</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>86</td>
			<td class="team">Tmou a stepí divočinou</td>
			<td>
					4728
			</td>
			<td>
					0
			</td>
			<td>
					90
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">941</td>
					<td class="done">968</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="done">945</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>87</td>
			<td class="team">Forever alone</td>
			<td>
					4718
			</td>
			<td>
					0
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">927</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">955</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">916</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">993</td>
		</tr>
			<tr class="line">
			<td>88</td>
			<td class="team">vass_ajtaci</td>
			<td>
					4673
			</td>
			<td>
					0
			</td>
			<td>
					20
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">903</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">956</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">973</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">920</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">941</td>
		</tr>
			<tr class="line">
			<td>89</td>
			<td class="team">Acervus Aren</td>
			<td>
					4291
			</td>
			<td>
					0
			</td>
			<td>
					470
			</td>
					<td class="empty">X</td>
					<td class="done">958</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">952</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">930</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">949</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>90</td>
			<td class="team">Alpha Team</td>
			<td>
					3819
			</td>
			<td>
					0
			</td>
			<td>
					40
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="done">908</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>91</td>
			<td class="team">Holky z naší školky</td>
			<td>
					3770
			</td>
			<td>
					0
			</td>
			<td>
					60
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">904</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="done">973</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>92</td>
			<td class="team">Červený trpaslík</td>
			<td>
					3763
			</td>
			<td>
					0
			</td>
			<td>
					110
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">926</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">974</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>93</td>
			<td class="team">God Bless Nám</td>
			<td>
					3739
			</td>
			<td>
					0
			</td>
			<td>
					90
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">912</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">948</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>94</td>
			<td class="team">Zlobři</td>
			<td>
					3036
			</td>
			<td>
					500
			</td>
			<td>
					340
			</td>
					<td class="empty">X</td>
					<td class="done">950</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">954</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">972</td>
		</tr>
			<tr class="line">
			<td>95</td>
			<td class="team">Lukas</td>
			<td>
					2828
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="done">964</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">911</td>
					<td class="done">953</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>96</td>
			<td class="team">Dreamteam GFXS</td>
			<td>
					2648
			</td>
			<td>
					0
			</td>
			<td>
					150
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">907</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">953</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">938</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>97</td>
			<td class="team">Ludolfovci</td>
			<td>
					1913
			</td>
			<td>
					0
			</td>
			<td>
					40
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>98</td>
			<td class="team">7MD squad</td>
			<td>
					1901
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">924</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>99</td>
			<td class="team">JÁ</td>
			<td>
					1878
			</td>
			<td>
					0
			</td>
			<td>
					80
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">964</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>100</td>
			<td class="team">Rudý hvězdy</td>
			<td>
					1872
			</td>
			<td>
					0
			</td>
			<td>
					20
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">961</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">931</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>101</td>
			<td class="team">antiManci</td>
			<td>
					1804
			</td>
			<td>
					0
			</td>
			<td>
					20
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">905</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">919</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>102</td>
			<td class="team">Boží Krakatit</td>
			<td>
					961
			</td>
			<td>
					0
			</td>
			<td>
					20
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>103</td>
			<td class="team">EgoOnanisti</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>104</td>
			<td class="team">Jemné Humory</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>105</td>
			<td class="team">Legna</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>106</td>
			<td class="team">Alces Sapiens</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>107</td>
			<td class="team">British Bismanol</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>108</td>
			<td class="team">FunkyTeam</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>109</td>
			<td class="team">IQtIQ</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>110</td>
			<td class="team">Kladeruby</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>111</td>
			<td class="team">Minimálne rýchlejšie</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>112</td>
			<td class="team">Organizátoři</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>113</td>
			<td class="team">Ferne Sterne</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>114</td>
			<td class="team">ovíněnci</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>115</td>
			<td class="team">Proč ne 32</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>116</td>
			<td class="team">šnek</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
	</table>
</div>
    </body>
</html>