<?xml version="1.0" encoding="utf-8" ?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs">
    <head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta http-equiv="content-language" content="cs" />
		<link rel="stylesheet" type="text/css" href="/css/main.css" />
		<link rel="stylesheet" type="text/css" href="/css/forms.css" />
		<link rel="stylesheet" type="text/css" href="/css/flashes.css" />
		<link href="/favicon.png" rel="icon" type="image/png" />
		<script type="text/javascript" src="/js/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="/js/jquery-ui-1.8.2.custom.min.js"></script>

		<title>
	    Interlos - Podrobné výsledky
		</title>

    </head>
    <body>
<div id="flashes">
</div><div id="score-stats-wrapper">
	<table id="score-stats" cellspacing="0">
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>1</td>
			<td class="team">segmentation fault</td>
			<td>
					29701
			</td>
			<td>
					4000
			</td>
			<td>
					30
			</td>
					<td class="done">1000</td>
					<td class="done">994</td>
					<td class="done">997</td>
					<td class="done">989</td>
					<td class="done">960</td>
					<td class="done">953</td>
					<td class="done">1000</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="done">1000</td>
					<td class="done">995</td>
					<td class="done">998</td>
					<td class="done">993</td>
					<td class="done">991</td>
					<td class="done">982</td>
					<td class="done">975</td>
					<td class="done">990</td>
					<td class="done">978</td>
					<td class="done">998</td>
					<td class="done">999</td>
					<td class="done">999</td>
					<td class="done">983</td>
					<td class="done">982</td>
					<td class="done">993</td>
					<td class="done">995</td>
					<td class="done">999</td>
					<td class="done">990</td>
		</tr>
			<tr class="line">
			<td>2</td>
			<td class="team">JÁDRO</td>
			<td>
					29655
			</td>
			<td>
					4000
			</td>
			<td>
					50
			</td>
					<td class="done">997</td>
					<td class="done">991</td>
					<td class="done">995</td>
					<td class="done">995</td>
					<td class="done">998</td>
					<td class="done">987</td>
					<td class="done">992</td>
					<td class="done">974</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="done">1000</td>
					<td class="done">977</td>
					<td class="done">998</td>
					<td class="done">989</td>
					<td class="done">981</td>
					<td class="done">969</td>
					<td class="done">979</td>
					<td class="done">1000</td>
					<td class="done">985</td>
					<td class="done">994</td>
					<td class="done">978</td>
					<td class="done">979</td>
					<td class="done">996</td>
					<td class="done">984</td>
					<td class="done">993</td>
					<td class="done">986</td>
		</tr>
			<tr class="line">
			<td>3</td>
			<td class="team">voy-a-ger</td>
			<td>
					28677
			</td>
			<td>
					4000
			</td>
			<td>
					110
			</td>
					<td class="done">998</td>
					<td class="done">997</td>
					<td class="done">969</td>
					<td class="done">980</td>
					<td class="done">1000</td>
					<td class="done">994</td>
					<td class="done">998</td>
					<td class="done">968</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="done">988</td>
					<td class="done">1000</td>
					<td class="done">993</td>
					<td class="done">992</td>
					<td class="done">1000</td>
					<td class="done">999</td>
					<td class="done">1000</td>
					<td class="done">996</td>
					<td class="done">998</td>
					<td class="done">1000</td>
					<td class="done">967</td>
					<td class="done">992</td>
					<td class="done">977</td>
					<td class="done">1000</td>
					<td class="done">989</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>4</td>
			<td class="team">Přizdisráči</td>
			<td>
					28547
			</td>
			<td>
					4000
			</td>
			<td>
					150
			</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="done">983</td>
					<td class="done">982</td>
					<td class="done">984</td>
					<td class="done">976</td>
					<td class="done">988</td>
					<td class="done">988</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="done">991</td>
					<td class="done">991</td>
					<td class="done">995</td>
					<td class="done">951</td>
					<td class="done">994</td>
					<td class="done">993</td>
					<td class="done">981</td>
					<td class="done">997</td>
					<td class="done">995</td>
					<td class="done">1000</td>
					<td class="done">997</td>
					<td class="done">981</td>
					<td class="done">973</td>
					<td class="done">973</td>
					<td class="done">998</td>
					<td class="done">998</td>
					<td class="done">999</td>
		</tr>
			<tr class="line">
			<td>5</td>
			<td class="team">Finální myšmaš</td>
			<td>
					26874
			</td>
			<td>
					3500
			</td>
			<td>
					190
			</td>
					<td class="done">993</td>
					<td class="done">995</td>
					<td class="done">956</td>
					<td class="done">956</td>
					<td class="done">976</td>
					<td class="done">996</td>
					<td class="done">983</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="done">997</td>
					<td class="done">954</td>
					<td class="done">971</td>
					<td class="done">997</td>
					<td class="done">979</td>
					<td class="done">973</td>
					<td class="done">998</td>
					<td class="done">992</td>
					<td class="done">984</td>
					<td class="done">991</td>
					<td class="done">957</td>
					<td class="done">984</td>
					<td class="done">955</td>
					<td class="done">999</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>6</td>
			<td class="team">Točená zmrzlina</td>
			<td>
					25961
			</td>
			<td>
					3500
			</td>
			<td>
					120
			</td>
					<td class="done">996</td>
					<td class="done">984</td>
					<td class="done">975</td>
					<td class="done">968</td>
					<td class="done">963</td>
					<td class="done">979</td>
					<td class="done">997</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="done">991</td>
					<td class="done">966</td>
					<td class="done">978</td>
					<td class="done">985</td>
					<td class="done">971</td>
					<td class="done">996</td>
					<td class="done">997</td>
					<td class="done">997</td>
					<td class="done">998</td>
					<td class="done">968</td>
					<td class="done">987</td>
					<td class="done">967</td>
					<td class="done">973</td>
					<td class="empty">X</td>
					<td class="done">983</td>
		</tr>
			<tr class="line">
			<td>7</td>
			<td class="team">Kokokel</td>
			<td>
					24914
			</td>
			<td>
					3500
			</td>
			<td>
					120
			</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="done">973</td>
					<td class="done">963</td>
					<td class="empty">X</td>
					<td class="done">967</td>
					<td class="done">987</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">990</td>
					<td class="done">998</td>
					<td class="done">944</td>
					<td class="done">991</td>
					<td class="done">996</td>
					<td class="done">964</td>
					<td class="done">992</td>
					<td class="done">989</td>
					<td class="done">971</td>
					<td class="done">984</td>
					<td class="done">985</td>
					<td class="done">947</td>
					<td class="done">959</td>
					<td class="done">990</td>
					<td class="done">990</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>8</td>
			<td class="team">Bazinga</td>
			<td>
					23669
			</td>
			<td>
					3000
			</td>
			<td>
					50
			</td>
					<td class="done">995</td>
					<td class="done">993</td>
					<td class="done">994</td>
					<td class="done">996</td>
					<td class="done">994</td>
					<td class="done">991</td>
					<td class="done">979</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="done">965</td>
					<td class="done">988</td>
					<td class="done">997</td>
					<td class="done">991</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="done">980</td>
					<td class="done">963</td>
					<td class="done">961</td>
					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="done">997</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>9</td>
			<td class="team">Já nic - to samo</td>
			<td>
					22047
			</td>
			<td>
					2500
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="done">985</td>
					<td class="done">954</td>
					<td class="done">985</td>
					<td class="done">942</td>
					<td class="done">970</td>
					<td class="done">963</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="done">987</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="done">973</td>
					<td class="done">983</td>
					<td class="done">977</td>
					<td class="done">982</td>
					<td class="done">999</td>
					<td class="done">981</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>10</td>
			<td class="team">Jeníčci</td>
			<td>
					21577
			</td>
			<td>
					3000
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="done">998</td>
					<td class="done">988</td>
					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="done">993</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
					<td class="done">963</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">966</td>
					<td class="done">975</td>
					<td class="done">982</td>
					<td class="done">988</td>
					<td class="done">962</td>
					<td class="done">985</td>
					<td class="done">997</td>
					<td class="done">961</td>
					<td class="done">956</td>
					<td class="done">981</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>11</td>
			<td class="team">Chlýftým</td>
			<td>
					21569
			</td>
			<td>
					2000
			</td>
			<td>
					50
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">968</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="done">974</td>
					<td class="done">980</td>
					<td class="done">967</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="done">961</td>
					<td class="done">997</td>
					<td class="done">996</td>
					<td class="done">982</td>
					<td class="done">989</td>
					<td class="done">973</td>
					<td class="empty">X</td>
					<td class="done">945</td>
					<td class="done">974</td>
					<td class="done">992</td>
					<td class="done">977</td>
					<td class="done">1000</td>
					<td class="done">980</td>
					<td class="done">995</td>
					<td class="done">984</td>
		</tr>
			<tr class="line">
			<td>12</td>
			<td class="team">Spící Volové</td>
			<td>
					21388
			</td>
			<td>
					2000
			</td>
			<td>
					110
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">942</td>
					<td class="done">935</td>
					<td class="done">955</td>
					<td class="done">983</td>
					<td class="done">961</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="done">986</td>
					<td class="done">990</td>
					<td class="done">976</td>
					<td class="done">993</td>
					<td class="done">991</td>
					<td class="done">969</td>
					<td class="done">996</td>
					<td class="done">949</td>
					<td class="done">958</td>
					<td class="done">985</td>
					<td class="done">994</td>
					<td class="done">988</td>
					<td class="done">987</td>
		</tr>
			<tr class="line">
			<td>13</td>
			<td class="team">IQtIQ</td>
			<td>
					20862
			</td>
			<td>
					2500
			</td>
			<td>
					150
			</td>
					<td class="done">994</td>
					<td class="done">990</td>
					<td class="done">953</td>
					<td class="done">924</td>
					<td class="done">958</td>
					<td class="done">940</td>
					<td class="done">985</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">978</td>
					<td class="empty">X</td>
					<td class="done">967</td>
					<td class="done">977</td>
					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="done">994</td>
					<td class="done">956</td>
					<td class="done">974</td>
					<td class="done">995</td>
					<td class="done">995</td>
					<td class="done">974</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>14</td>
			<td class="team">Nejnekvazidiagonalizovávatelnější</td>
			<td>
					20113
			</td>
			<td>
					2500
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="done">990</td>
					<td class="done">957</td>
					<td class="done">981</td>
					<td class="done">994</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="done">957</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="done">988</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="done">986</td>
					<td class="done">956</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="done">988</td>
		</tr>
			<tr class="line">
			<td>15</td>
			<td class="team">ROFLCOPTER!</td>
			<td>
					19958
			</td>
			<td>
					1500
			</td>
			<td>
					200
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">964</td>
					<td class="done">1000</td>
					<td class="done">980</td>
					<td class="done">936</td>
					<td class="done">991</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">983</td>
					<td class="done">1000</td>
					<td class="done">993</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="done">942</td>
					<td class="done">973</td>
					<td class="done">955</td>
					<td class="done">974</td>
					<td class="done">999</td>
					<td class="done">996</td>
					<td class="done">994</td>
					<td class="done">994</td>
		</tr>
			<tr class="line">
			<td>16</td>
			<td class="team">nechci-uvést</td>
			<td>
					19955
			</td>
			<td>
					2500
			</td>
			<td>
					90
			</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="done">988</td>
					<td class="done">985</td>
					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">967</td>
					<td class="done">953</td>
					<td class="done">983</td>
					<td class="done">973</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">972</td>
					<td class="done">966</td>
					<td class="done">941</td>
					<td class="empty">X</td>
					<td class="done">957</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="done">985</td>
		</tr>
			<tr class="line">
			<td>17</td>
			<td class="team">Žufouni</td>
			<td>
					19538
			</td>
			<td>
					2000
			</td>
			<td>
					90
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="done">994</td>
					<td class="done">986</td>
					<td class="done">978</td>
					<td class="done">969</td>
					<td class="done">966</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">959</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="done">949</td>
					<td class="done">981</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="done">969</td>
					<td class="done">968</td>
					<td class="done">992</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>18</td>
			<td class="team">Dyslektická bezkontxetová gramatika</td>
			<td>
					19123
			</td>
			<td>
					2500
			</td>
			<td>
					40
			</td>
					<td class="done">999</td>
					<td class="done">998</td>
					<td class="done">1000</td>
					<td class="done">967</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">956</td>
					<td class="done">977</td>
					<td class="empty">X</td>
					<td class="done">998</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="done">969</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="done">971</td>
					<td class="done">968</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="done">981</td>
					<td class="empty">X</td>
					<td class="done">963</td>
					<td class="empty">X</td>
					<td class="done">974</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>19</td>
			<td class="team">Niečo vymyslíme</td>
			<td>
					18684
			</td>
			<td>
					2000
			</td>
			<td>
					20
			</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">981</td>
					<td class="done">976</td>
					<td class="done">982</td>
					<td class="done">997</td>
					<td class="done">978</td>
					<td class="done">987</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="done">980</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="done">993</td>
					<td class="done">945</td>
					<td class="done">975</td>
					<td class="done">979</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>20</td>
			<td class="team">felis perenis</td>
			<td>
					18661
			</td>
			<td>
					2000
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">991</td>
					<td class="done">965</td>
					<td class="done">999</td>
					<td class="done">998</td>
					<td class="done">974</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="done">976</td>
					<td class="done">998</td>
					<td class="done">987</td>
					<td class="done">974</td>
					<td class="done">984</td>
					<td class="done">980</td>
					<td class="done">993</td>
					<td class="done">958</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="empty">X</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>21</td>
			<td class="team">Tweety neni kura</td>
			<td>
					18622
			</td>
			<td>
					2000
			</td>
			<td>
					80
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">965</td>
					<td class="done">993</td>
					<td class="done">996</td>
					<td class="done">965</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="done">996</td>
					<td class="done">977</td>
					<td class="done">969</td>
					<td class="done">974</td>
					<td class="done">990</td>
					<td class="done">971</td>
					<td class="done">993</td>
					<td class="done">997</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>22</td>
			<td class="team">Trosečníci</td>
			<td>
					18584
			</td>
			<td>
					2000
			</td>
			<td>
					60
			</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="done">986</td>
					<td class="done">942</td>
					<td class="done">992</td>
					<td class="done">986</td>
					<td class="done">995</td>
					<td class="done">964</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">968</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="done">977</td>
					<td class="done">962</td>
					<td class="done">995</td>
					<td class="done">986</td>
					<td class="done">994</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>23</td>
			<td class="team">Heuréka</td>
			<td>
					17499
			</td>
			<td>
					2000
			</td>
			<td>
					20
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">980</td>
					<td class="done">945</td>
					<td class="done">968</td>
					<td class="done">945</td>
					<td class="done">981</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="done">950</td>
					<td class="empty">X</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="done">983</td>
					<td class="done">996</td>
					<td class="done">964</td>
					<td class="done">946</td>
					<td class="done">951</td>
					<td class="done">966</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>24</td>
			<td class="team">Diamhra</td>
			<td>
					16643
			</td>
			<td>
					2000
			</td>
			<td>
					20
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="done">973</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">965</td>
					<td class="done">981</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">965</td>
					<td class="done">974</td>
					<td class="done">986</td>
					<td class="done">967</td>
					<td class="done">987</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="done">991</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>25</td>
			<td class="team">Troufalci</td>
			<td>
					16561
			</td>
			<td>
					2000
			</td>
			<td>
					40
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="done">997</td>
					<td class="done">988</td>
					<td class="done">946</td>
					<td class="done">968</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">953</td>
					<td class="done">948</td>
					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="done">971</td>
					<td class="done">946</td>
					<td class="done">992</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>26</td>
			<td class="team">Vepřová kachna</td>
			<td>
					15845
			</td>
			<td>
					1500
			</td>
			<td>
					240
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="done">925</td>
					<td class="done">993</td>
					<td class="done">989</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">951</td>
					<td class="done">955</td>
					<td class="done">980</td>
					<td class="done">964</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">954</td>
					<td class="done">961</td>
					<td class="done">993</td>
					<td class="done">976</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>27</td>
			<td class="team">Divize nulou</td>
			<td>
					15613
			</td>
			<td>
					2000
			</td>
			<td>
					50
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="done">953</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="done">972</td>
					<td class="done">985</td>
					<td class="done">979</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="done">971</td>
					<td class="done">975</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="done">936</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>28</td>
			<td class="team">British Bismanol</td>
			<td>
					15056
			</td>
			<td>
					1500
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">920</td>
					<td class="done">973</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="done">974</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="done">957</td>
					<td class="done">983</td>
					<td class="done">953</td>
					<td class="done">968</td>
					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">998</td>
		</tr>
			<tr class="line">
			<td>29</td>
			<td class="team">Jak se nám líbí!</td>
			<td>
					14630
			</td>
			<td>
					2000
			</td>
			<td>
					50
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">941</td>
					<td class="done">957</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="done">978</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="done">978</td>
					<td class="done">988</td>
					<td class="done">965</td>
					<td class="done">948</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">1000</td>
		</tr>
			<tr class="line">
			<td>30</td>
			<td class="team">Bednajt v Bidetu</td>
			<td>
					14557
			</td>
			<td>
					2000
			</td>
			<td>
					110
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">930</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">967</td>
					<td class="done">981</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="done">962</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">991</td>
					<td class="done">990</td>
					<td class="done">986</td>
					<td class="done">970</td>
					<td class="done">958</td>
					<td class="done">966</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">991</td>
					<td class="empty">X</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>31</td>
			<td class="team">Tykve</td>
			<td>
					14434
			</td>
			<td>
					1000
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">951</td>
					<td class="done">926</td>
					<td class="done">978</td>
					<td class="done">935</td>
					<td class="done">957</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="done">964</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="empty">X</td>
					<td class="done">937</td>
					<td class="empty">X</td>
					<td class="done">962</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="empty">X</td>
					<td class="done">989</td>
		</tr>
			<tr class="line">
			<td>32</td>
			<td class="team">Voy-b-ger</td>
			<td>
					13585
			</td>
			<td>
					1000
			</td>
			<td>
					90
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="done">987</td>
					<td class="done">979</td>
					<td class="done">962</td>
					<td class="done">955</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">948</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="empty">X</td>
					<td class="done">981</td>
		</tr>
			<tr class="line">
			<td>33</td>
			<td class="team">Chróúst?</td>
			<td>
					13562
			</td>
			<td>
					1000
			</td>
			<td>
					140
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">933</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">996</td>
					<td class="done">978</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">950</td>
					<td class="done">987</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="done">990</td>
					<td class="empty">X</td>
					<td class="done">968</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">964</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>34</td>
			<td class="team">Sníme psy</td>
			<td>
					13222
			</td>
			<td>
					500
			</td>
			<td>
					50
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">957</td>
					<td class="done">964</td>
					<td class="done">989</td>
					<td class="done">970</td>
					<td class="done">999</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="done">980</td>
					<td class="done">983</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">991</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>35</td>
			<td class="team">Pirate Shrimp</td>
			<td>
					12616
			</td>
			<td>
					1000
			</td>
			<td>
					170
			</td>
					<td class="empty">X</td>
					<td class="done">1000</td>
					<td class="done">950</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">958</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="done">995</td>
					<td class="done">971</td>
					<td class="done">999</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>36</td>
			<td class="team">Stěrači</td>
			<td>
					12603
			</td>
			<td>
					1000
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">961</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="done">938</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="done">935</td>
					<td class="empty">X</td>
					<td class="done">1000</td>
					<td class="done">988</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>37</td>
			<td class="team">Piumino corto con imbottitura- cappuccio staccabile</td>
			<td>
					12572
			</td>
			<td>
					1000
			</td>
			<td>
					90
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">963</td>
					<td class="done">960</td>
					<td class="done">964</td>
					<td class="done">984</td>
					<td class="done">965</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">940</td>
					<td class="done">978</td>
					<td class="done">979</td>
					<td class="done">998</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">991</td>
		</tr>
			<tr class="line">
			<td>38</td>
			<td class="team">Carpe Diem</td>
			<td>
					12531
			</td>
			<td>
					1000
			</td>
			<td>
					40
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">946</td>
					<td class="done">913</td>
					<td class="done">972</td>
					<td class="done">950</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">971</td>
					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="done">950</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="done">965</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>39</td>
			<td class="team">para-N-methylaminoazobenzen</td>
			<td>
					12448
			</td>
			<td>
					1000
			</td>
			<td>
					150
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="done">992</td>
					<td class="done">956</td>
					<td class="empty">X</td>
					<td class="done">962</td>
					<td class="done">973</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">955</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="done">928</td>
					<td class="done">957</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>40</td>
			<td class="team">&lt;put your name here&gt;</td>
			<td>
					12173
			</td>
			<td>
					1500
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">939</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">998</td>
					<td class="done">981</td>
					<td class="empty">X</td>
					<td class="done">938</td>
					<td class="done">968</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>41</td>
			<td class="team">Night Wolves</td>
			<td>
					11648
			</td>
			<td>
					1000
			</td>
			<td>
					120
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">971</td>
					<td class="done">978</td>
					<td class="done">977</td>
					<td class="done">973</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="done">979</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>42</td>
			<td class="team">Lososi na sněhu</td>
			<td>
					11205
			</td>
			<td>
					1500
			</td>
			<td>
					60
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="done">963</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="done">989</td>
					<td class="done">942</td>
					<td class="done">954</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="done">997</td>
		</tr>
			<tr class="line">
			<td>43</td>
			<td class="team">Zase pozdě</td>
			<td>
					11023
			</td>
			<td>
					500
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">958</td>
					<td class="empty">X</td>
					<td class="done">961</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="done">956</td>
					<td class="done">984</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">943</td>
					<td class="empty">X</td>
					<td class="done">930</td>
					<td class="done">950</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>44</td>
			<td class="team">Mazentovi bustri</td>
			<td>
					10960
			</td>
			<td>
					500
			</td>
			<td>
					130
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">934</td>
					<td class="done">946</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="done">966</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="done">974</td>
					<td class="done">990</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">932</td>
					<td class="empty">X</td>
					<td class="done">934</td>
					<td class="done">956</td>
					<td class="done">990</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>45</td>
			<td class="team">GJGT 1</td>
			<td>
					10916
			</td>
			<td>
					500
			</td>
			<td>
					270
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">933</td>
					<td class="done">977</td>
					<td class="empty">X</td>
					<td class="done">968</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="done">973</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">955</td>
					<td class="done">955</td>
					<td class="done">998</td>
					<td class="done">960</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">992</td>
		</tr>
			<tr class="line">
			<td>46</td>
			<td class="team">KVÍK!</td>
			<td>
					10673
			</td>
			<td>
					0
			</td>
			<td>
					140
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="empty">X</td>
					<td class="done">991</td>
					<td class="done">984</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">952</td>
					<td class="done">952</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>47</td>
			<td class="team">Stoosum</td>
			<td>
					10581
			</td>
			<td>
					1000
			</td>
			<td>
					110
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">962</td>
					<td class="done">955</td>
					<td class="empty">X</td>
					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="done">949</td>
					<td class="empty">X</td>
					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">993</td>
		</tr>
			<tr class="line">
			<td>48</td>
			<td class="team">x&#039;; DROP TABLE users; --</td>
			<td>
					10485
			</td>
			<td>
					0
			</td>
			<td>
					230
			</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="done">987</td>
					<td class="done">952</td>
					<td class="done">981</td>
					<td class="done">977</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">956</td>
					<td class="done">963</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="done">970</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>49</td>
			<td class="team">Bedrunky</td>
			<td>
					10184
			</td>
			<td>
					500
			</td>
			<td>
					80
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">961</td>
					<td class="done">991</td>
					<td class="done">958</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="done">968</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">964</td>
					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>50</td>
			<td class="team">Sráči</td>
			<td>
					10140
			</td>
			<td>
					500
			</td>
			<td>
					40
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="done">931</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="done">977</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">945</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">931</td>
					<td class="done">971</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>51</td>
			<td class="team">32 Grosse Schoko Bananen</td>
			<td>
					9478
			</td>
			<td>
					0
			</td>
			<td>
					160
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">967</td>
					<td class="done">947</td>
					<td class="done">959</td>
					<td class="done">948</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">967</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="done">947</td>
					<td class="empty">X</td>
					<td class="done">969</td>
					<td class="done">970</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>52</td>
			<td class="team">Paralaxa</td>
			<td>
					9218
			</td>
			<td>
					500
			</td>
			<td>
					50
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">928</td>
					<td class="done">987</td>
					<td class="done">1000</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">936</td>
					<td class="done">965</td>
					<td class="empty">X</td>
					<td class="done">1000</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>53</td>
			<td class="team">Dokonalost Netreba</td>
			<td>
					9141
			</td>
			<td>
					500
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">973</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="done">934</td>
					<td class="empty">X</td>
					<td class="done">964</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>54</td>
			<td class="team">dušou blondínky</td>
			<td>
					9043
			</td>
			<td>
					500
			</td>
			<td>
					130
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">944</td>
					<td class="done">939</td>
					<td class="done">997</td>
					<td class="done">971</td>
					<td class="done">959</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">952</td>
					<td class="done">946</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>55</td>
			<td class="team">agenti</td>
			<td>
					9008
			</td>
			<td>
					500
			</td>
			<td>
					170
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">949</td>
					<td class="done">945</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="done">974</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="done">941</td>
					<td class="done">954</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>56</td>
			<td class="team">Sólista</td>
			<td>
					8622
			</td>
			<td>
					1000
			</td>
			<td>
					50
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">947</td>
					<td class="done">916</td>
					<td class="empty">X</td>
					<td class="done">939</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">973</td>
					<td class="done">972</td>
					<td class="done">932</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>57</td>
			<td class="team">Po Netu</td>
			<td>
					8481
			</td>
			<td>
					0
			</td>
			<td>
					130
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">974</td>
					<td class="done">919</td>
					<td class="empty">X</td>
					<td class="done">951</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="done">965</td>
					<td class="done">960</td>
					<td class="done">944</td>
					<td class="done">962</td>
					<td class="done">954</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>58</td>
			<td class="team">Babřik kačoty</td>
			<td>
					8313
			</td>
			<td>
					500
			</td>
			<td>
					20
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="done">981</td>
					<td class="empty">X</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">973</td>
					<td class="done">964</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>59</td>
			<td class="team">supermuf</td>
			<td>
					8304
			</td>
			<td>
					500
			</td>
			<td>
					30
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="done">937</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="done">994</td>
					<td class="done">991</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>60</td>
			<td class="team">Maséři jako hovado</td>
			<td>
					8095
			</td>
			<td>
					500
			</td>
			<td>
					80
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="done">941</td>
					<td class="empty">X</td>
					<td class="done">955</td>
					<td class="done">984</td>
					<td class="done">965</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">961</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">933</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>61</td>
			<td class="team">Kajakteam</td>
			<td>
					8070
			</td>
			<td>
					500
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">952</td>
					<td class="done">929</td>
					<td class="done">990</td>
					<td class="done">944</td>
					<td class="done">964</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">952</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">953</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>62</td>
			<td class="team">Uvidím E</td>
			<td>
					8070
			</td>
			<td>
					500
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="done">932</td>
					<td class="done">930</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">957</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">974</td>
					<td class="done">944</td>
					<td class="done">957</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>63</td>
			<td class="team">jmmnj</td>
			<td>
					8032
			</td>
			<td>
					500
			</td>
			<td>
					210
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">958</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">975</td>
					<td class="done">967</td>
					<td class="done">989</td>
					<td class="done">946</td>
					<td class="done">961</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">980</td>
		</tr>
			<tr class="line">
			<td>64</td>
			<td class="team">GBN</td>
			<td>
					7708
			</td>
			<td>
					0
			</td>
			<td>
					60
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">959</td>
					<td class="done">959</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="done">960</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="done">965</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>65</td>
			<td class="team">Odkaz Věry Pohlové</td>
			<td>
					7636
			</td>
			<td>
					0
			</td>
			<td>
					40
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">955</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="done">963</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">939</td>
					<td class="done">969</td>
					<td class="done">966</td>
					<td class="done">949</td>
					<td class="done">963</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>66</td>
			<td class="team">7MD squad</td>
			<td>
					7613
			</td>
			<td>
					0
			</td>
			<td>
					60
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">938</td>
					<td class="done">973</td>
					<td class="done">965</td>
					<td class="done">947</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">961</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="done">945</td>
					<td class="done">962</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>67</td>
			<td class="team">Náhodný výběr</td>
			<td>
					7419
			</td>
			<td>
					1000
			</td>
			<td>
					320
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">955</td>
					<td class="done">927</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">962</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">956</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="done">968</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">995</td>
		</tr>
			<tr class="line">
			<td>68</td>
			<td class="team">Zrychlený TEP</td>
			<td>
					7252
			</td>
			<td>
					500
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="done">974</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">980</td>
					<td class="done">954</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">982</td>
		</tr>
			<tr class="line">
			<td>69</td>
			<td class="team">tmp</td>
			<td>
					7204
			</td>
			<td>
					500
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="done">917</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">953</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="done">976</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>70</td>
			<td class="team">Sloniky</td>
			<td>
					6729
			</td>
			<td>
					0
			</td>
			<td>
					30
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">932</td>
					<td class="empty">X</td>
					<td class="done">954</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">929</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>71</td>
			<td class="team">Megatim</td>
			<td>
					6642
			</td>
			<td>
					1000
			</td>
			<td>
					80
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">935</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">964</td>
					<td class="done">958</td>
					<td class="done">962</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">953</td>
					<td class="empty">X</td>
					<td class="done">950</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>72</td>
			<td class="team">Sova pálená</td>
			<td>
					6136
			</td>
			<td>
					500
			</td>
			<td>
					90
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">927</td>
					<td class="done">949</td>
					<td class="done">967</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">962</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">961</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>73</td>
			<td class="team">Arawn</td>
			<td>
					6109
			</td>
			<td>
					500
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>
					<td class="done">983</td>
					<td class="done">948</td>
					<td class="done">923</td>
					<td class="done">961</td>
					<td class="empty">X</td>
					<td class="done">954</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">940</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>74</td>
			<td class="team">PPP</td>
			<td>
					6087
			</td>
			<td>
					500
			</td>
			<td>
					120
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">937</td>
					<td class="done">940</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">961</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="done">935</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>75</td>
			<td class="team">Lamka</td>
			<td>
					5827
			</td>
			<td>
					0
			</td>
			<td>
					20
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="done">949</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">968</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="done">963</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>76</td>
			<td class="team">Fialové Kocky</td>
			<td>
					5682
			</td>
			<td>
					0
			</td>
			<td>
					60
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">943</td>
					<td class="done">975</td>
					<td class="done">966</td>
					<td class="done">952</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">951</td>
					<td class="done">955</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>77</td>
			<td class="team">AMNESIA: BLUESCREEN OF DEATH</td>
			<td>
					5640
			</td>
			<td>
					0
			</td>
			<td>
					60
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">936</td>
					<td class="done">915</td>
					<td class="done">962</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">948</td>
					<td class="done">981</td>
					<td class="done">958</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>78</td>
			<td class="team">Temná hmota</td>
			<td>
					5258
			</td>
			<td>
					500
			</td>
			<td>
					10
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">928</td>
					<td class="done">951</td>
					<td class="done">983</td>
					<td class="done">941</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">965</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>79</td>
			<td class="team">Škrkny</td>
			<td>
					4744
			</td>
			<td>
					0
			</td>
			<td>
					50
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">934</td>
					<td class="done">970</td>
					<td class="done">980</td>
					<td class="done">963</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">947</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>80</td>
			<td class="team">KAMS</td>
			<td>
					4741
			</td>
			<td>
					0
			</td>
			<td>
					60
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">950</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">951</td>
					<td class="empty">X</td>
					<td class="done">943</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>81</td>
			<td class="team">V.I.Peace</td>
			<td>
					4221
			</td>
			<td>
					500
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">958</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">956</td>
					<td class="done">960</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">947</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>82</td>
			<td class="team">Nulová šance</td>
			<td>
					4178
			</td>
			<td>
					500
			</td>
			<td>
					120
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">914</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">967</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">963</td>
					<td class="empty">X</td>
					<td class="done">954</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>83</td>
			<td class="team">Genius proTeam !</td>
			<td>
					3753
			</td>
			<td>
					0
			</td>
			<td>
					120
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">921</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">996</td>
		</tr>
			<tr class="line">
			<td>84</td>
			<td class="team">No Chance</td>
			<td>
					3733
			</td>
			<td>
					0
			</td>
			<td>
					60
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">926</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">964</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">931</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>85</td>
			<td class="team">Lorenzův bagr na velbloudy</td>
			<td>
					3690
			</td>
			<td>
					0
			</td>
			<td>
					60
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">929</td>
					<td class="done">936</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">952</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">933</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>86</td>
			<td class="team">Limetky</td>
			<td>
					3677
			</td>
			<td>
					0
			</td>
			<td>
					150
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">940</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="done">967</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>87</td>
			<td class="team">Dream team</td>
			<td>
					3637
			</td>
			<td>
					0
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">945</td>
					<td class="done">918</td>
					<td class="empty">X</td>
					<td class="done">937</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">937</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>88</td>
			<td class="team">A - Team OKAPP</td>
			<td>
					3629
			</td>
			<td>
					0
			</td>
			<td>
					250
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">962</td>
					<td class="done">974</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>89</td>
			<td class="team">Hlavy otevřené</td>
			<td>
					2778
			</td>
			<td>
					0
			</td>
			<td>
					80
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">931</td>
					<td class="done">943</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>90</td>
			<td class="team">!!!BAZINGA!!!</td>
			<td>
					2744
			</td>
			<td>
					0
			</td>
			<td>
					90
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">938</td>
					<td class="empty">X</td>
					<td class="done">957</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">939</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>91</td>
			<td class="team">Mrkve</td>
			<td>
					1925
			</td>
			<td>
					0
			</td>
			<td>
					10
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">948</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>92</td>
			<td class="team">Matesovic</td>
			<td>
					1923
			</td>
			<td>
					0
			</td>
			<td>
					20
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>93</td>
			<td class="team">Gymnázium Děčín</td>
			<td>
					1865
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">922</td>
					<td class="empty">X</td>
					<td class="done">943</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>94</td>
			<td class="team">WeSwearSheWas18</td>
			<td>
					1616
			</td>
			<td>
					0
			</td>
			<td>
					280
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">958</td>
					<td class="empty">X</td>
					<td class="done">938</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>95</td>
			<td class="team">Eskymáci</td>
			<td>
					1000
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>96</td>
			<td class="team">Aww..</td>
			<td>
					956
			</td>
			<td>
					0
			</td>
			<td>
					20
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>97</td>
			<td class="team">alvapka</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>98</td>
			<td class="team">Anonymous</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>99</td>
			<td class="team">Awesome!</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>100</td>
			<td class="team">Bazinga!</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>101</td>
			<td class="team">C4.A Gymnázium Děčín</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>102</td>
			<td class="team">Dûnyain</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>103</td>
			<td class="team">gls</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>104</td>
			<td class="team">GYBONi</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>105</td>
			<td class="team">iSchemy</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>106</td>
			<td class="team">Los Muchachos</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>107</td>
			<td class="team">Románek</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>108</td>
			<td class="team">RUBIK POWER</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>109</td>
			<td class="team">Vega</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>110</td>
			<td class="team">Absolutní rým</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>111</td>
			<td class="team">Ešte sa dohodneme</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>112</td>
			<td class="team">Five Muskegeeks</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>113</td>
			<td class="team">Oravci</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>114</td>
			<td class="team">silentTeam</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>115</td>
			<td class="team">T.O.W.M.</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>116</td>
			<td class="team">DoomHammer and FrostMourne</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>117</td>
			<td class="team">Outsideři</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>118</td>
			<td class="team">Specialita šéfkuchaře</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>119</td>
			<td class="team">Správný nápad</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>120</td>
			<td class="team">Šmoulové</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>121</td>
			<td class="team">Organizátoři</td>
			<td>
					-10
			</td>
			<td>
					0
			</td>
			<td>
					10
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>122</td>
			<td class="team">Filip a Tom Integra</td>
			<td>
					-70
			</td>
			<td>
					0
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>123</td>
			<td class="team">Broskvičky</td>
			<td>
					-210
			</td>
			<td>
					0
			</td>
			<td>
					210
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
	</table>
</div>
    </body>
</html>
