<?php
header('HTTP/1.1 503 Service Unavailable');
header('Retry-After: 300'); // 5 minutes in seconds
?>
<!DOCTYPE html>
<html lang="cs">
<head>
	<meta charset="utf-8">
	<meta name="robots" content="noindex">
	<title>Selhání systému</title>
	<style>
		body { color: #333; background: white; width: 500px; margin: 100px auto }
		h1 { font: bold 47px/1.5 sans-serif; margin: .6em 0 }
		p { font: 21px/1.5 Georgia,serif; margin: 1.5em 0 }
		small { font-size: 70%; color: gray }
	</style>
</head>
<body>
	<h1>Selhání systému</h1>
	<p>Systém je kvůli kritické chybě momentálně odstaven, více informací hledejte na stránce s krizovými informacemi nebo ve svých e-mailových schránkách.</p>
</body>
</html>

<?php
exit();